const actions = {
    UPDATE_INDEX: 'UPDATE_INDEX',
    UPDATE_CARD_SLOT_WITH_CARD: 'UPDATE_CARD_SLOT_WITH_CARD',
    CARD_USED: 'CARD_USED',
    PLAYER_UPDATE: 'PLAYER_UPDATE',
    PLAYER_NUM_SELECTION_SHOW: 'PLAYER_NUM_SELECTION_SHOW'
};

export default actions;